# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReproqTui < Formula
  desc "Modern realtime TUI dashboard for Reproq Worker."
  homepage "https://github.com/adpena/reproq-tui"
  version "0.0.107"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adpena/reproq-tui/releases/download/v0.0.107/reproq-tui_0.0.107_darwin_amd64.tar.gz"
      sha256 "6d3acd957bb8ad45b83fafa0ba4d54ef01e677cd7129ea920ce0b12461a308c2"

      def install
        bin.install "reproq-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adpena/reproq-tui/releases/download/v0.0.107/reproq-tui_0.0.107_darwin_arm64.tar.gz"
      sha256 "3a85e3ed53639ae155fb24f4fbcc14b260fe3031da761b65a81007183da78a55"

      def install
        bin.install "reproq-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adpena/reproq-tui/releases/download/v0.0.107/reproq-tui_0.0.107_linux_amd64.tar.gz"
      sha256 "0f2280e5001599839ff0d9e4f9f957887d4d893aec165a1ce5c372bcdbe18147"
      def install
        bin.install "reproq-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adpena/reproq-tui/releases/download/v0.0.107/reproq-tui_0.0.107_linux_arm64.tar.gz"
      sha256 "1ceddc539fab80f99d1d8539885326a1357804d43b14d72d9b17e2d7437a88c3"
      def install
        bin.install "reproq-tui"
      end
    end
  end
end
