# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReproqTui < Formula
  desc "Modern realtime TUI dashboard for Reproq Worker."
  homepage "https://github.com/adpena/reproq-tui"
  version "0.0.102"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adpena/reproq-tui/releases/download/v0.0.102/reproq-tui_0.0.102_darwin_amd64.tar.gz"
      sha256 "d791bd2f14bcca3ce844f23c0a91934af4e8639b8f1d2acfaf211fadfed96f13"

      def install
        bin.install "reproq-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adpena/reproq-tui/releases/download/v0.0.102/reproq-tui_0.0.102_darwin_arm64.tar.gz"
      sha256 "19ea19e985a886f6cd9dcbedfde422b6d926a5e6bd13ce8e434070a755ddb340"

      def install
        bin.install "reproq-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adpena/reproq-tui/releases/download/v0.0.102/reproq-tui_0.0.102_linux_amd64.tar.gz"
      sha256 "8672f8b27b46bdf336f3d1993532e00d5a0632824fbf435d37c4308fa7c0ba3a"
      def install
        bin.install "reproq-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adpena/reproq-tui/releases/download/v0.0.102/reproq-tui_0.0.102_linux_arm64.tar.gz"
      sha256 "031d8d6a903208e38ba55fdbe950b6f3d0293b0076bc777064784eac6204ad1b"
      def install
        bin.install "reproq-tui"
      end
    end
  end
end
